name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "response-time"
