name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "site"
